---
abstract: "A smart, easy and powerful way to access/create XML files/data."
author:
  - 'Graciliano M. P. <gm@virtuasites.com.br>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-Smart
no_index:
  directory:
    - t
    - inc
requires:
  Object::MultiType: 0.03
version: 1.73
